apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: fluentbit
data:
  fluent-bit.conf: |
    # [SERVICE]
        # Flush      5
        # Daemon     off
        # Log_Level  info

    [INPUT]
        Name        forward
        # Listen      0.0.0.0
        # Port        24224

    [OUTPUT]
        Name    forward
        Match   *
        Host    homin.ddns.net
        Port    24224

    [OUTPUT]
        Name stdout
        Match *
