apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: fluentbit
data:

  plugins.conf: |
    [PLUGINS]
      Path /plugins/out_telegram.so

  flb.conf: |
    [SERVICE]
        plugins_file /conf/plugins.conf
        # Flush      5
        # Daemon     off
        # Log_Level  info

    [INPUT]
        Name        forward
        # Listen      0.0.0.0
        # Port        24224

    [FILTER]
        Name    rewrite_tag
        Match   app.*
        Rule    $alert ^(.+)$ notify.$1 true
        # Rule    $level ^warn notify.telegram true
        Rule    $level ^error notify.telegram true
        Rule    $level ^fatal notify.telegram true

    [OUTPUT]
        Name    telegram
        Match   notify.telegram
        api_token               ${TG_API_TOKEN}
        room_ids                ${TG_ROOM_IDS}
        timestamp_location      Asia/Seoul
        timestamp_layout        20060102 15:04:05
        optional_keys           level,program,ver,hostname
        suppress_duplication    yes
        suppress_timeout        10s

    [OUTPUT]
        Name          forward
        Match         *
        Host          homin.ddns.net
        Port          24224
        Shared_Key    ${FLD_SHARED_KEY}
        Self_Hostname ${HOSTNAME}
        tls           on
        tls.verify    off
  
    [OUTPUT]
        Name stdout
        Match *
 
