apiVersion: v1
kind: Service
metadata:
  name: fluent
  labels:
    app: fluent
spec:
  type: ClusterIP
  ports:
    - port: 24224
      targetPort: 24224
  selector:
    app: fluentbit
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  labels:
    app: fluentbit
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      containers:
        - name: fluent-bit
          image: gcr.io/homin-dev/flb-tg:latest
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /conf/
          env:
            - name: FLD_SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: fld_shared_key
            - name: TG_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: telegram_apitoken
            - name: TG_ROOM_IDS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: telegram_room_id
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
