apiVersion: v1
kind: Service
metadata:
  name: resume
  labels:
    app: resume
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: resume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume
  name: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      containers:
      - image: 'gcr.io/homin-dev/resume:latest'
        name: resume
        ports:
          - containerPort: 8080