apiVersion: v1
kind: Service
metadata:
  name: dsb-api
  labels:
    app: dsb-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dsb-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dsb-api
  name: dsb-api
spec:
  replicas: 3
  minReadySeconds: 1
  # strategy:  
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0 
  selector:
    matchLabels:
      app: dsb-api
  template:
    metadata:
      labels:
        app: dsb-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      containers:
        - name: diagrams-be
          image: 'gcr.io/homin-dev/diagrams_be:latest'
          args: ["-l", ":8080", "-p", "/dsb-api"]
          # args: ["-p", "/dsb"]
          # resources: 
          #   limits: 
          #       cpu: 10m 
          #       memory: 256Mi 
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run