apiVersion: v1
kind: Service
metadata:
  name: ingress
  labels:
    app: ingress
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress
  name: ingress
  # annotations:
  #   "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  minReadySeconds: 1
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      containers:
        - image: 'gcr.io/homin-dev/ingress:v1.2.2'
          args: ["-p", "ingress", "-c", "/conf/links.yaml"]
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name          
          name: ingress
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ingress-links
              subPath: links.yaml
              mountPath: /conf/links.yaml
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "10m"
      volumes:
        - name: ingress-links
          configMap:
            name: ingress-links
        - name: mysecret
          secret:
            secretName: mysecret
