apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 9001
  selector:
    app: mosquitto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: 'eclipse-mosquitto:latest'
        name: mosquitto
        ports:
          - containerPort: 9001
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf